<?php

namespace App\Charts\Bar;

use App\Charts\Base;

/**
 * Bar chart class
 */
class Bar extends Base
{
    /**
     * Set data bar chart
     * @param DataBar[] $dataBar Data bar
     * @return void
     */
    public function setDataBar(array $dataBar): void
    {

    }

    protected function load(): void
    {
        parent::load(); // TODO: Change the autogenerated stub
    }
}
